[package]
name = "intentscript-compiler"
version.workspace = true
edition.workspace = true

[dependencies]
intentscript-core = { path = "../intentscript-core" }
intentscript-parser = { path = "../intentscript-parser" }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
quickcheck = { workspace = true }
quickcheck_macros = { workspace = true }
